name: Build README

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: update readme
        run: |-
          python build.py
          cat README.md

      - name: commit and push if readme changed
        run: |-
          git diff
          git config --global user.email "readme-bot@fossapps.com"
          git config --global user.name "readme-bot"
          git diff --quiet || (git add README.md && git commit -m "update README")
          git push
