name: Build README

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: update readme
        run: |-
          python scripts/build.py

      - name: config bot
        run: |-
          git config --global user.email "readme-bot@fossapps.com"
          git config --global user.name "readme-bot"

      - name: commit and push if something changed
        run: |-
          git add -A
          git commit -m "`bot: rebuild content`" || exit 0
          git push
