name: Build README

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: update readme
        run: |-
          python scripts/build.py

      - name: commit and push if readme changed
        run: |-
          git diff
          git config --global user.email "readme-bot@fossapps.com"
          git config --global user.name "readme-bot"
          git diff --quiet || (git add README.md categories/* && git commit -m "bot: rebuild")
          git push
